//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string u_firstname { get; set; }
        public string u_lastname { get; set; }
        public string u_email { get; set; }
        public string u_password { get; set; }
        public string u_phonenumber { get; set; }
        public string u_promo { get; set; }
        public string u_preference { get; set; }
    }
}
